
@startuml{run_func_on_target.png}

participant "ConTest\n(Debugger API)" as fw
participant "Target\n(ECU)" as trg


== Start ==

fw -> trg: trigger function 'xyz' execution on target
trg -> fw: function 'xyz' execution started
fw -> trg: function 'xyz' executed?
trg -> fw: no. still executing ...
note over fw, trg: Debugger keep on asking about\nexecution status till timeout or\n some error reported by target
fw -> trg: function 'xyz' executed?
trg -> fw: yes. function 'xyz' executed

rnote over fw
 check execution state and
 report error to user if any
endrnote

== End ==

@enduml
