
@startuml{core.png}

state Core {
    state Runner {
        WrapTests: Wrap user selected tests\nwith "setup.pytest" content (setup-teardown)
        LoadTests: Create a list of tests with wrapped data
        SetupWatchers: Initialize test watchers, e.g. for reporting

        note left of Execution
            repeat for all loaded tests
        end note

        state Execution: Start all loaded tests execution. Report using watchers.

        state Reporting: Done within the watchers during test execution
    }

    [*] -> Runner: Triggered by\nUI Controller\nor Main in auto mode [1]
    Runner -> SetupWatchers: Prepare test execution [2]
    SetupWatchers -> WrapTests
    WrapTests -> LoadTests
    Execution -right-> Reporting
    LoadTests -down-> Execution: Test execution [3]

    Execution -down-> [*]: Send signals to UI Controller\nabout test(s) status [4]
}

@enduml
